workspace(name = "skaffold")


load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# Begin Docker set up.

# This is based on the following instructions:
# https://github.com/bazelbuild/rules_docker/blob/cda964418102ac1f63dce6ed988d14b9d1b9f075/README.md#setup

# Download the rules_docker repository at release v0.14.1
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b1e80761a8a8243d03ebca8845e9cc1ba6c82ce7c5179ce2b295cd36f7e394bf",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.25.0/rules_docker-v0.25.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()
container_repositories()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
  name = "java_base",
  registry = "gcr.io",
  repository = "distroless/java",
  # 'tag' is also supported, but digest is encouraged for reproducibility.
  digest = "sha256:deadbeef",
)

load(
      "@io_bazel_rules_docker//go:image.bzl",
          _go_image_repos = "repositories",
)

_go_image_repos()
